# Application properties
spring.application.name=BioSteel Teams
spring.application.version=0.0.1

# Development settings
app.development.enabled=false
app.development.include-verification-code=false
app.default-avatar.url-template=https://getstream.imgix.net/images/random_svg/{initials}.png

# Server
server.port=8080
logging.file.name=/var/log/biosteel-api/application.log
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# File
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/biosteel
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=biosteel

# HikariCP specific settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email Configuration
email.from-email=${FROM_EMAIL}
email.support-email=${SUPPORT_EMAIL}
email.verification-base-url=${VERIFICATION_BASE_URL}
email.password-reset-base-url=${RESET_PASSWORD_BASE_URL}

# JWT
users.security.token.secret=${JWT_SECRET}
users.security.token.accessTokenExpirationInSeconds=86400000
users.security.token.refreshTokenExpirationInSeconds=86400000

# Security Configuration
users.security.failedLoginAttempts=10
users.security.accountLockoutDuration=30

# Swagger UI path
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
server.forward-headers-strategy=framework
openapi.server.url=${OPEN_API_SERVER}

# AWS S3 Configuration
aws.s3.bucket=${S3_BUCKET}
aws.s3.url=${S3_URL}
aws.s3.region=${S3_REGION}
aws.s3.access-key=${S3_ACCESS_KEY}
aws.s3.secret-key=${S3_SECRET_KEY}


# Get Stream
stream.api-key=${STREAM_API_KEY}
stream.api-secret=${STREAM_API_SECRET}
stream.api-base-url=https://chat-us-east-1.stream-io-api.com

# Firebase Cloud Messaging Configuration
firebase.type=${FIREBASE_TYPE:service_account}
firebase.project.id=${FIREBASE_PROJECT_ID}
firebase.private.key.id=${FIREBASE_PRIVATE_KEY_ID}
firebase.private.key=${FIREBASE_PRIVATE_KEY}
firebase.client.email=${FIREBASE_CLIENT_EMAIL}
firebase.client.id=${FIREBASE_CLIENT_ID}
firebase.auth.uri=${FIREBASE_AUTH_URI:https://accounts.google.com/o/oauth2/auth}
firebase.token.uri=${FIREBASE_TOKEN_URI:https://oauth2.googleapis.com/token}
firebase.auth.provider.x509.cert.url=${FIREBASE_AUTH_PROVIDER_CERT_URL:https://www.googleapis.com/oauth2/v1/certs}
firebase.client.x509.cert.url=${FIREBASE_CLIENT_CERT_URL}

# FCM Configuration
firebase.timeout.connect=5000
firebase.timeout.read=10000
firebase.batch.size=500

# Firebase Topic Naming Conventions
firebase.topic.prefix=biosteel_
firebase.topic.team=team_
firebase.topic.event=event_
firebase.topic.global=global